apiVersion: v1
kind: Namespace
metadata:
  name: train-book
  namespace: krishna    
  spec:
    selector:
      app: train-book
      ports:
      -protocol: TCP
        port: 8080
        targetPort: 8080
        type: loadBalancer